### ISSUE TITLE
Dockerfile missing can't run on heroku

### ISSUE THREAD

**Issue by FristyFlakes** [dcdunkan/pastebin-bot#1]

**Comment by dcdunkan** [comment]
Now it should work. I am a beginner in everything. So, please forgive. I fixed the issue by setting the stack value to `heroku-20` as they said in the build error log. I tried making one. And it is worked. So, please try once more, and if there was an error again for you please let me know. If there wasn't, please report it here. Thankyou.

**Comment by FristyFlakes** [comment]
Deployed Successfully Now.. Closing Issue

**Comment by dcdunkan** [comment]
Alright. Thankyou for reporting the issue. It was my fault. I deployed it by connecting my github account in heroku. So, i thought it works perfectly. Anyway thankyou
